fs: verity: Drop all of the desc* identifiers
Nuke all of the desc-related identifiers, as these are not declared anywhere in the kernel tree and were only added via upstream.

Fixes the following issue:
error: use of undeclared identifier 'desc'
        if (sig_size > desc_size - sizeof(*desc)) {
                                           ^
error: use of undeclared identifier 'desc_size'
        if (sig_size > desc_size - sizeof(*desc)) {
                       ^

Signed-off-by: prathamdubey2005 <134331217+prathamdubey2005@users.noreply.github.com>